experiment:
  dataset: ncf_ml1m
  data_config:
    strategy: fixed
    train_path: ../data/{0}/ml-1m.train.rating
    test_path: ../data/{0}/ml-1m.test.rating
  prefiltering:
    - strategy: global_threshold
      threshold: 4
    - strategy: iterative_k_core
      core: 10
  binarize: True
  splitting:
    test_splitting:
        strategy: random_subsampling
        test_ratio: 0.2
  negative_sampling:
    strategy: fixed
    files: ["/home/cheggynho/PycharmProjects/elliot/data/ncf_ml1m/ml-1m.test.negative"]
  top_k: 10
  evaluation:
    cutoffs: 10
    simple_metrics: [nDCG, recall]
#  gpu: -1
  external_models_path: ../external/models/__init__.py
  models:
#    Random:
#      meta:
#        save_recs: False
#    external.MostPop:
#      meta:
#        verbose: True
#        save_recs: False
#        save_weights: False
#    MultiVAE:
#      meta:
##        hyper_max_evals: 3
##        hyper_opt_alg: tpe
##        validation_rate: 10
#        verbose: True
##        save_weights: True
#        save_recs: False
#        restore: False
#        optimize_internal_loss: True
#      lr: 0.002718457840118028
#      epochs: 10
#      intermediate_dim: 91
#      latent_dim: 100
#      batch_size: -1
#      dropout_pkeep: 1
#      reg_lambda: 0.01
#    external.RendleMF:
#      meta:
#        verbose: True
#        save_recs: False
#      epochs: 10
#      factors: 10
#      lr: 0.01
#      reg: 0.0025
#    external.EASER:
#      meta:
#        verbose: True
#        save_recs: False
#      l2_norm: 3e3
#    external.RP3beta:
#      meta:
#        verbose: True
#        save_recs: False
#      neighborhood: 100
#      alpha: 1
#      beta: 0.6
#      normalize_similarity: True
#    external.NeuMF: #from the original paper + Rendle
#      meta:
#        hyper_max_evals: 20
#        hyper_opt_alg: tpe
#        verbose: True
#        save_recs: True
#        validation_rate: 1
#        # optimize_internal_loss: True
#      mf_factors:  [8, 16, 32, 64, 128, 256]
#      dropout: 0
#      is_mf_train: True
#      is_mlp_train: True
#      batch_size: [128, 256, 512, 1024]
#      epochs: 50
#      lr: [0.0001, 0.0005, 0.001, 0.005]
#      m: 4
    RecommendationFolder:
      folder: /home/cheggynho/Downloads/recsys_first
#    external.ProxyRecommender:
#      path: /home/cheggynho/PycharmProjects/elliot/data/ncf_ml1m/ml-1m.test.rating
#    external.RendleMF: # from original paper
#      meta:
#        hyper_max_evals: 20
#        hyper_opt_alg: tpe
#        verbose: True
#        save_recs: True
#        # optimize_internal_loss: True
#      epochs: 50 # 256 original paper but 50 comes from NeuMF paper
#      factors: 8 #[8, 16, 32, 64, 128, 256]
#      lr: [0.001, 0.003, 0.01]
#      reg: [0.001, 0.003, 0.01]
#      m: 4
#      seed: 42
#    external.iALS:
#      meta:
#        verbose: True
#        save_recs: False
#      factors: 20
#      alpha: 1
#      epsilon: 1
#      reg: 0.001