# Structured logging defaults for Elliot.
# Levels can be overridden to be more/less chatty depending on the run.
app_name: elliot
console_level: DEBUG
file_level: DEBUG
max_bytes: 5000000
backup_count: 5
json_file_logs: true
include_location: true
color_console: true
